# Generated by Django 5.2.3 on 2025-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_table_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
